name: Curse Build

on:
  push:
    tags:
    - '*'

    paths-ignore:
    - ".github/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: BigWigsMods/packager@v2
      with:
        args: -p 606496 -a e56nDWG9
      env:
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        CF_API_KEY: ${{ secrets.plusmouse_curseforge }}
        WAGO_API_TOKEN: ${{ secrets.plusmouse_wago }}
